#!/bin/bash
# Copyright 2022 Toyota Research Institute

CHANGE_BRANCH=$1
SRC_FOLDER=$2

echo try checking out ${CHANGE_BRANCH}
vcs custom $SRC_FOLDER --args branch -f $CHANGE_BRANCH origin/$CHANGE_BRANCH > /dev/null || true
vcs custom $SRC_FOLDER --args merge --no-edit $CHANGE_BRANCH  > /dev/null || true
DIFF=$(vcs diff -s $SRC_FOLDER | tr -d '.\n')
if [ ! -z "$DIFF" ]; then
    echo "Have merge conflicts!"
    echo $DIFF
    exit 1
fi
vcs status $SRC_FOLDER
