name: gcc

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  PACKAGE_NAME: maliput_viz
  ROS_DISTRO: foxy

jobs:
  compile_and_test:
    name: Compile and test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/maliput/ci_foxy_image:latest
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - uses: ros-tooling/action-ros-ci@v0.4
      id: action_ros_ci_step
      with:
        package-name: ${{ env.PACKAGE_NAME }}
        target-ros2-distro: ${{ env.ROS_DISTRO }}
        vcs-repo-file-url: ${GITHUB_WORKSPACE}/.github/dependencies.repos
